import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

import ModalProvider from "@/providers/modal-provider";
import { ModalStoreProvider } from "@/providers/modal-store-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalStoreProvider>
          <main className="flex flex-col w-screen h-screen">{children}</main>
          <ModalProvider />
          <Toaster />
        </ModalStoreProvider>
      </body>
    </html>
  );
}
